name: BeTPA
version: '${version}'
main: me.lukiiy.beTPA.BeTPA
authors: [ Lukiiy ]
description: A little TPA plugin, for beta.
commands:
  tpa:
    usage: "/<command> <player>"
    description: Sends a teleport request to a player
  tpaccept:
    usage: "/<command> [player]"
    description: Accepts a teleport request from one or more players
  tpadeny:
    usage: "/<command> [player]"
    description: Denies a teleport request from one or more players
  tpareload:
    usage: "/<command>"
    description: Reloads the plugin